[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

port = 10000

address = "0.0.0.0"

[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[browser]
gatherUsageStats = false


[global]
developmentMode = false

[client]
showErrorDetails = false
